In [1]:
from sci_fi_parser import parse_folder

/home/matimo/opinnot/ohjelmisto-projekti/Sci-Fi-Parser/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
result = parse_folder(input_dir="../train_data/small_pdfs", output_dir="output")

Loading weights: 100%|██████████| 360/360 [00:00<00:00, 3972.48it/s]
/home/matimo/opinnot/ohjelmisto-projekti/Sci-Fi-Parser/.venv/lib/python3.13/site-packages/paddle/utils/cpp_extension/extension_utils.py:718: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('PP-OCRv6_medium_det', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/matimo/.paddlex/official_models/PP-OCRv6_medium_det`.
Creating model: ('PP-OCRv6_medium_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/matimo/.paddlex/official_models/PP-OCRv6_medium_rec`.

ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport
ReduceMeanCheckIfOneDNNSupport

  0%|          | 0/1 [00:00<?, ?it/s]WARNING:root:VLM extraction failed for image_id=bd37ab2a-7c58-4223-8d21-56492378fc9f: Client error '404 Not Found' for url 'http://localhost:11434/v1/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
100%|██████████| 1/1 [00:00<00:00, 15.88it/s]

In [4]:
result.summary()

{'pdf_count': 1, 'image_count': 23}

In [19]:
len(result.images)
#result.images

23

In [ ]:
for image_id, image in result.images.items():
    print("Image ID:")
    print(image_id)

    print("\nMetadata:")
    print(image["metadata"])

    print("\nClassification:")
    print(image["classification"]["result"])

    print("\nClassification scores:")
    print(image["classification"]["raw"])

    print("\nOCR:")
    print(image["ocrcv"]["result"])

    print("\nVLM:")
    print(image["vlm"]["result"])

    print("\nImage path:")
    print(image["output"]["path"])

    print("\nFull image object:")
    print(image)

    break

Image ID:
b6a6d931-2250-4dfd-8d83-83808e2bb574

Metadata:
{'extraction': {'pdf_id': '40100209-d98a-4e7d-bb8b-68e124d3ac39', 'page_number': '1', 'source_type': 'embedded_image'}, 'classification': {}, 'ocrcv': {}, 'vlm': {}}

OCR:


VLM:
{}
{'metadata': {'extraction': {'pdf_id': '40100209-d98a-4e7d-bb8b-68e124d3ac39', 'page_number': '1', 'source_type': 'embedded_image'}, 'classification': {}, 'ocrcv': {}, 'vlm': {}}, 'output': {'path': PosixPath('/home/matimo/opinnot/ohjelmisto-projekti/Sci-Fi-Parser/notebooks/temp/extracted_images/b6a6d931-2250-4dfd-8d83-83808e2bb574.png')}, 'classification': {'result': 'logo', 'raw': {'logo': 0.87107253074646, 'photograph': 0.0005798386409878731, 'icon': 0.03638235852122307, 'engineering_drawing': 0.001129453768953681, 'line_chart': 0.0012316068168729544, 'bar_chart': 0.0020784889347851276, 'other': 0.018837478011846542, 'table': 0.0001503996318206191, 'flow_chart': 6.979692989261821e-05, 'screenshot_from_computer': 0.00011029853340005502, 'signature': 0.04746261239051819, 'screenshot_from_manual': 0.0002597954007796943, 'geographical_map': 1.541639539937023e-05, 'pie_chart': 1.0572145583864767e-05, 'page_thumbnail': 0.000512134691234678, 'stamp': 0.008551458828151226, 'music': 0.005301951430737972, 'calendar': 0.004589559976011515, 'qr_code': 0.00030291033908724785, 'bar_code': 0.0009326768340542912, 'full_page_image': 0.0001293512323172763, 'scatter_plot': 1.2545780919026583e-05, 'chemistry_structure': 0.00016259797848761082, 'topographical_map': 1.759971200954169e-05, 'crossword_puzzle': 7.651020132470876e-05, 'box_plot': 2.0063211195520125e-05}}, 'ocrcv': {'result': '', 'raw': {}}, 'vlm': {'result': {}, 'raw': {}}}

In [7]:
charts = result.charts_dataframe()
series = result.series_dataframe()
points = result.points_dataframe()

In [17]:
#charts.head()
charts

,chart_id,pdf_id,page_number,source_type,image_path,chart_type,model,created_at,total_duration,load_duration,eval_count,eval_duration
0,b6a6d931-2250-4dfd-8d83-83808e2bb574,40100209-d98a-4e7d-bb8b-68e124d3ac39,1,embedded_image,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
1,e701c090-861a-4bbc-8f12-40e34578dd29,40100209-d98a-4e7d-bb8b-68e124d3ac39,1,embedded_image,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
2,bd37ab2a-7c58-4223-8d21-56492378fc9f,40100209-d98a-4e7d-bb8b-68e124d3ac39,10,embedded_image,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
3,af065f9f-845c-42bd-99c9-77561e7a484f,40100209-d98a-4e7d-bb8b-68e124d3ac39,18,embedded_image,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
4,d8cccdb0-a9fc-47a8-8de2-5a6f0f438467,40100209-d98a-4e7d-bb8b-68e124d3ac39,18,embedded_image,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
5,18320975-7c02-49d0-b617-076d9090062d,40100209-d98a-4e7d-bb8b-68e124d3ac39,1,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
6,e7e5fd53-d747-401d-86a4-493d17c72f61,40100209-d98a-4e7d-bb8b-68e124d3ac39,2,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
7,aa7c9ecc-5b0f-480c-ac4b-71c06860e08d,40100209-d98a-4e7d-bb8b-68e124d3ac39,3,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
8,1f36cd08-936a-446d-b14d-289a4aa013d8,40100209-d98a-4e7d-bb8b-68e124d3ac39,4,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
9,60f36083-144b-43c1-9030-52e064e95abb,40100209-d98a-4e7d-bb8b-68e124d3ac39,5,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
10,38845c12-07c6-45e2-bfed-d8f797a73c8b,40100209-d98a-4e7d-bb8b-68e124d3ac39,6,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
11,5c6ca586-8ef5-4455-825c-73e756adccbc,40100209-d98a-4e7d-bb8b-68e124d3ac39,7,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
12,718c0b06-59cb-4eb3-9382-b4722e5a828d,40100209-d98a-4e7d-bb8b-68e124d3ac39,8,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
13,e6852599-2ce6-43e4-93c1-a0c681e8910d,40100209-d98a-4e7d-bb8b-68e124d3ac39,9,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
14,c9849ba4-2e3b-4b85-9dd8-722773b856af,40100209-d98a-4e7d-bb8b-68e124d3ac39,10,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
15,a15e1d45-1def-466a-9a96-4483f9c7eed0,40100209-d98a-4e7d-bb8b-68e124d3ac39,11,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
16,f0c8f7fd-1635-49bb-9b2e-7476a526d28d,40100209-d98a-4e7d-bb8b-68e124d3ac39,12,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
17,21aefe93-dabc-45ef-80c9-9019a33d9d00,40100209-d98a-4e7d-bb8b-68e124d3ac39,13,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
18,234fab0b-5dc1-4833-9b7f-600bcd720490,40100209-d98a-4e7d-bb8b-68e124d3ac39,14,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
19,0e9b8988-f353-4089-8b8d-371d904faffe,40100209-d98a-4e7d-bb8b-68e124d3ac39,15,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
20,f6228cd3-a85b-4c32-aa2a-448382539cb1,40100209-d98a-4e7d-bb8b-68e124d3ac39,16,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
21,14888230-70b7-46f2-bf49-2217fcb85560,40100209-d98a-4e7d-bb8b-68e124d3ac39,17,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None
22,65db270a-eb72-4b5e-b5e7-b0a0b00dc003,40100209-d98a-4e7d-bb8b-68e124d3ac39,18,vector_drawing,/home/matimo/opinnot/ohjelmisto-projekti/Sci-F...,None,None,None,None,None,None,None

In [10]:
series.head()

Empty DataFrame
Columns: []
Index: []

In [11]:
points.head()

Empty DataFrame
Columns: []
Index: []

In [12]:
# Number of charts by type
charts["chart_type"].value_counts()

Series([], Name: count, dtype: int64)

In [13]:
# Count extracted points per chart
points.groupby("chart_id").size().sort_values(ascending=False).head(10)

KeyError: 'chart_id'

In [14]:
# Inspect one chart's data

chart_id = points["chart_id"].iloc[0]

points[points["chart_id"] == chart_id]

KeyError: 'chart_id'

In [15]:
import duckdb

In [16]:
duckdb.sql("""

SELECT
    chart_id,
    AVG(y) AS average_y
FROM points
GROUP BY chart_id
ORDER BY average_y DESC
LIMIT 10

""").df()

InvalidInputException: Invalid Input Error: Need a DataFrame with at least one column